[supervisord]
nodaemon=true

[program:bind9]
command=/usr/sbin/named -f -c /etc/bind/named.conf -u root
autorestart=true
user=root

[program:bind9-api]
command=/usr/local/bin/bind9-api --config /etc/bind9-api/config.yaml
directory=/etc/bind9-api
autorestart=true
user=root