[supervisord]
nodaemon=true
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisord.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:bind9]
command=/usr/sbin/named -f -c /etc/bind/named.conf -u root
autorestart=true
user=root

[program:bind9-api]
command=/usr/local/bin/bind9-api --config /etc/bind9-api/config.yaml
directory=/etc/bind9-api
autorestart=true
user=root