version: '3.7'
services:
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: ehm-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - TZ=${TZ:?err}
      - UPLOAD_LIMIT=900M
    ports:
      - '2329:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      eh_network:
        ipv4_address: 172.1.0.5
    volumes:
     - /sessions
     - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    #  - ./signon-script.php:/etc/phpmyadmin/signon-script.php
    #  - ./signon.php:/etc/phpmyadmin/signon.php
    #  - ./examples:/var/www/html/examples/
     - ./ehm-authentication:/var/www/html/ehm-authentication/
     - ./theme/:/www/themes/theme/
networks:
  eh_network:
    external: true
    name: eh_network