services:
  db:
    build: .
    image: nahidacm/eh-mariadb:11.5.2
    container_name: ehm-db-container
    restart: unless-stopped
    volumes:
      - './dbdata:/var/lib/mysql'
      - '/epiclabs23/eh/oneclick-apps/sql-files:/epiclabs23/eh/oneclick-apps/sql-files'
    networks:
      eh_network:
        ipv4_address: 172.1.0.6
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:?err}
      - MARIADB_USER=${MARIADB_USER:?err}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:?err}
      - TZ=${TZ:?err}
networks:
  eh_network:
    external: true
    name: eh_network